const CHATGPT_BASE_URL = "https://chatgpt.com/";

const sourceTitleEl = document.getElementById("sourceTitle") as HTMLDivElement | null;
const sourceUrlEl = document.getElementById("sourceUrl") as HTMLDivElement | null;
const copyPromptBtn = document.getElementById("copyPromptBtn") as HTMLButtonElement | null;
const reinsertBtn = document.getElementById("reinsertBtn") as HTMLButtonElement | null;
const settingsBtn = document.getElementById("settingsBtn") as HTMLButtonElement | null;
const closeBtn = document.getElementById("closeBtn") as HTMLButtonElement | null;
const languageMismatchPrompt = document.getElementById("languageMismatchPrompt") as HTMLDivElement | null;
const languageMismatchText = document.getElementById("languageMismatchText") as HTMLDivElement | null;
const continueSessionBtn = document.getElementById("continueSessionBtn") as HTMLButtonElement | null;
const startNewSessionBtn = document.getElementById("startNewSessionBtn") as HTMLButtonElement | null;
const cancelSessionBtn = document.getElementById("cancelSessionBtn") as HTMLButtonElement | null;
const chatgptFrame = document.getElementById("chatgptFrame") as HTMLIFrameElement | null;
const panelTabId = getPanelTabId();

/**
 * Extension session id currently loaded into the ChatGPT iframe.
 *
 * This is not a ChatGPT conversation or thread id. It is generated by the
 * extension in background.ts, stored in chrome.storage.local, and passed to
 * ChatGPT in the iframe URL hash as dwc_session=... so the content script can
 * match the iframe page to the prompt it should insert.
 *
 * The side panel starts with no iframe session loaded, so this value is null.
 * During startup and storage changes, the side panel reads this panel tab's
 * extension session id from storage. When that id differs from
 * this local value, the side panel updates this value to the new id and
 * navigates the iframe to a ChatGPT URL containing that session hash.
 *
 * Keeping this local copy prevents repeated storage events from reloading the
 * iframe for the same session, which would discard the current ChatGPT composer
 * state.
 */
let currentIframeSessionId: string | null = null;

void init();

async function init(): Promise<void> {
    if (
        !sourceTitleEl ||
        !sourceUrlEl ||
        !copyPromptBtn ||
        !reinsertBtn ||
        !settingsBtn ||
        !closeBtn ||
        !languageMismatchPrompt ||
        !languageMismatchText ||
        !continueSessionBtn ||
        !startNewSessionBtn ||
        !cancelSessionBtn ||
        !chatgptFrame
    ) {
        console.error("[chatgpt-companion] side panel DOM elements not found");
        return;
    }

    if (panelTabId === null) {
        console.error("[chatgpt-companion] side panel tab id not found");
        return;
    }

    attachEvents();
    attachStorageListener();

    await renderSource();
    await renderLanguageMismatchPrompt();
    await syncIframeSession();
}

/**
 * Watches extension storage for this panel tab's discussion data.
 */
function attachStorageListener(): void {
    chrome.storage.onChanged.addListener(async (changes, areaName) => {
        if (areaName !== "local") {
            return;
        }

        if (changes["discussions"] || changes["tabSessionIds"]) {
            await renderSource();
            await syncIframeSession();
        }

        if (changes["pendingLanguageMismatches"]) {
            await renderLanguageMismatchPrompt();
        }
    });
}

/**
 * Binds side panel controls for copying, reinserting, and closing the current
 * discussion session.
 */
function attachEvents(): void {
    copyPromptBtn?.addEventListener("click", async () => {
        const discussion = await getPanelDiscussion();
        await navigator.clipboard.writeText(discussion?.prompt ?? "");
    });

    reinsertBtn?.addEventListener("click", async () => {
        if (panelTabId === null) {
            return;
        }

        const storage = (await chrome.storage.local.get([
            "discussions",
            "tabSessionIds"
        ])) as StorageShape;
        const sessionId = storage.tabSessionIds?.[String(panelTabId)];
        if (!sessionId || !storage.discussions?.[sessionId]) {
            return;
        }

        const discussions = { ...storage.discussions };

        // bumping stamp and resetting consumed makes the content script treat
        // this existing prompt as a new insertion request
        discussions[sessionId] = {
            ...discussions[sessionId],
            stamp: Date.now(),
            consumed: false
        };

        await chrome.storage.local.set({ discussions });
    });

    settingsBtn?.addEventListener("click", () => {
        void chrome.runtime.openOptionsPage();
    });

    continueSessionBtn?.addEventListener("click", () => {
        void continuePanelDiscussion();
    });

    startNewSessionBtn?.addEventListener("click", () => {
        void startNewPanelDiscussion();
    });

    cancelSessionBtn?.addEventListener("click", () => {
        void clearPanelLanguageMismatch();
    });

    closeBtn?.addEventListener("click", async () => {
        if (panelTabId === null) {
            return;
        }

        const storage = (await chrome.storage.local.get([
            "discussions",
            "tabSessionIds",
            "pendingLanguageMismatches"
        ])) as StorageShape;
        const tabKey = String(panelTabId);
        const sessionId = storage.tabSessionIds?.[tabKey];
        const discussions = { ...(storage.discussions ?? {}) };
        const tabSessionIds = { ...(storage.tabSessionIds ?? {}) };

        if (sessionId) {
            delete discussions[sessionId];
            delete tabSessionIds[tabKey];
        }

        await chrome.storage.local.set({
            discussions,
            tabSessionIds,
            pendingLanguageMismatches: removePanelLanguageMismatch(storage.pendingLanguageMismatches),
            closeDiscussionSessionId: sessionId
        });

        // give the content script a short window to observe closeDiscussionSessionId
        // and remove ChatGPT's transient draft before the panel tears down
        await new Promise((resolve) => setTimeout(resolve, 150));

        window.close();
    });
}

/**
 * Renders a tab-scoped settings mismatch prompt when one is pending.
 */
async function renderLanguageMismatchPrompt(): Promise<void> {
    if (!languageMismatchPrompt || !languageMismatchText) {
        return;
    }

    const mismatch = await getPanelLanguageMismatch();

    if (!mismatch) {
        languageMismatchPrompt.classList.add("hidden");
        languageMismatchText.replaceChildren();
        return;
    }

    languageMismatchText.replaceChildren(
        createMismatchIntro(),
        createMismatchRow("Current discussion", mismatch.currentPromptTemplateName, mismatch.currentLanguage),
        createMismatchRow(
            "New discussion",
            mismatch.requestedPromptTemplateName,
            mismatch.requestedLanguage,
            mismatch.requestedSourceChanged ? "different source or selection" : undefined
        )
    );
    languageMismatchPrompt.classList.remove("hidden");
}

function createMismatchIntro(): HTMLElement {
    const intro = document.createElement("div");
    intro.textContent = "This tab already has a discussion. Choose how to handle the new request.";
    return intro;
}

function createMismatchRow(label: string, templateName: string, language: string, detail?: string): HTMLElement {
    const row = document.createElement("div");
    row.className = "languageMismatchRow";
    row.textContent = `${label}: ${templateName} | ${language}${detail ? ` | ${detail}` : ""}`;
    return row;
}

/**
 * Clears this panel tab's pending settings mismatch prompt.
 */
async function clearPanelLanguageMismatch(): Promise<void> {
    if (panelTabId === null) {
        return;
    }

    const storage = (await chrome.storage.local.get("pendingLanguageMismatches")) as StorageShape;
    await chrome.storage.local.set({
        pendingLanguageMismatches: removePanelLanguageMismatch(storage.pendingLanguageMismatches)
    });
}

/**
 * Adds the new request prompt to the current restored discussion.
 */
async function continuePanelDiscussion(): Promise<void> {
    if (!continueSessionBtn) {
        return;
    }

    const mismatch = await getPanelLanguageMismatch();
    if (!mismatch) {
        return;
    }

    continueSessionBtn.disabled = true;

    try {
        const response = await chrome.runtime.sendMessage<RuntimeMessage, RuntimeResponse>({
            type: "continue-discussion",
            tabId: mismatch.tabId,
            requestedPromptTemplateId: mismatch.requestedPromptTemplateId,
            requestedLinkUrl: mismatch.requestedLinkUrl,
            selectionText: mismatch.selectionText
        });

        if (!response?.ok) {
            throw new Error(response?.error || "Continue operation failed");
        }
    } catch (error) {
        console.error("[chatgpt-companion] continue discussion failed", error);
    } finally {
        continueSessionBtn.disabled = false;
    }
}

/**
 * Starts a separate discussion from the selected request.
 */
async function startNewPanelDiscussion(): Promise<void> {
    if (!startNewSessionBtn) {
        return;
    }

    const mismatch = await getPanelLanguageMismatch();
    if (!mismatch) {
        return;
    }

    startNewSessionBtn.disabled = true;

    try {
        const response = await chrome.runtime.sendMessage<RuntimeMessage, RuntimeResponse>({
            type: "start-new-discussion",
            tabId: mismatch.tabId,
            requestedPromptTemplateId: mismatch.requestedPromptTemplateId,
            requestedLinkUrl: mismatch.requestedLinkUrl,
            selectionText: mismatch.selectionText
        });

        if (!response?.ok) {
            throw new Error(response?.error || "Start new operation failed");
        }
    } catch (error) {
        console.error("[chatgpt-companion] start new discussion failed", error);
    } finally {
        startNewSessionBtn.disabled = false;
    }
}

/**
 * Returns the pending settings mismatch for this panel tab.
 */
async function getPanelLanguageMismatch(): Promise<PendingLanguageMismatch | null> {
    if (panelTabId === null) {
        return null;
    }

    const storage = (await chrome.storage.local.get("pendingLanguageMismatches")) as StorageShape;
    return storage.pendingLanguageMismatches?.[String(panelTabId)] ?? null;
}

/**
 * Removes this panel tab's settings mismatch from a mismatch map.
 */
function removePanelLanguageMismatch(
    pendingLanguageMismatches: Record<string, PendingLanguageMismatch> | undefined
): Record<string, PendingLanguageMismatch> {
    if (panelTabId === null) {
        return pendingLanguageMismatches ?? {};
    }

    const nextPendingLanguageMismatches = { ...(pendingLanguageMismatches ?? {}) };
    delete nextPendingLanguageMismatches[String(panelTabId)];
    return nextPendingLanguageMismatches;
}

/**
 * Renders the source title and URL for this panel tab's current discussion.
 */
async function renderSource(): Promise<void> {
    if (!sourceTitleEl || !sourceUrlEl) {
        return;
    }

    const discussion = await getPanelDiscussion();
    const source = discussion?.source;

    if (!source) {
        sourceTitleEl.textContent = "Page not selected";
        sourceUrlEl.textContent = "URL not found";
        return;
    }

    sourceTitleEl.textContent = source.title || "Page title is missing";
    sourceUrlEl.textContent = source.url || "URL is missing";
}

/**
 * Keeps the embedded ChatGPT frame aligned with this panel tab's
 * discussion session.
 *
 * The background script creates one extension session id per source tab and
 * stores that mapping in chrome.storage.local.tabSessionIds. The side panel is
 * bound to one source tab through its tabId URL parameter and can be notified
 * for the same tab/session more than once during startup and storage updates, so
 * this function treats storage as the source of truth and only navigates the
 * iframe when the desired session actually changes.
 *
 * Navigating the iframe is meaningful because buildChatUrl embeds the session
 * id in the ChatGPT URL hash. The content script running inside ChatGPT reads
 * that hash, looks up the matching stored prompt, and inserts it into the
 * composer.
 *
 * Reassigning chatgptFrame.src for the same session would reload ChatGPT and
 * can discard the user's current unsent composer text, so currentIframeSessionId
 * is used as a local reload guard.
 */
async function syncIframeSession(): Promise<void> {
    if (!chatgptFrame) {
        return;
    }

    if (panelTabId === null) {
        return;
    }

    const data = (await chrome.storage.local.get([
        "discussions",
        "tabSessionIds"
    ])) as StorageShape;
    const sessionId = data.tabSessionIds?.[String(panelTabId)];

    if (!sessionId) {
        if (currentIframeSessionId !== null) {
            currentIframeSessionId = null;
            chatgptFrame.src = CHATGPT_BASE_URL;
        }

        return;
    }

    // loading the same session again would reload ChatGPT and discard the
    // current composer state
    if (sessionId === currentIframeSessionId) {
        return;
    }

    currentIframeSessionId = sessionId;
    chatgptFrame.src = buildChatUrl(sessionId, data.discussions?.[sessionId]?.chatUrl);
}

/**
 * Creates the ChatGPT URL that carries the extension session id in the hash.
 *
 * The hash is intentionally extension-owned state, not a ChatGPT conversation
 * id. It lets the ChatGPT content script identify which discussion entry in
 * chrome.storage.local belongs to this iframe load.
 */
function buildChatUrl(sessionId: string, chatUrl?: string): string {
    const url = new URL(chatUrl || CHATGPT_BASE_URL);
    url.hash = `dwc_session=${encodeURIComponent(sessionId)}`;
    return url.toString();
}

/**
 * Returns the discussion state associated with this panel tab.
 */
async function getPanelDiscussion(): Promise<DiscussionState | null> {
    if (panelTabId === null) {
        return null;
    }

    const data = (await chrome.storage.local.get([
        "discussions",
        "tabSessionIds"
    ])) as StorageShape;
    const sessionId = data.tabSessionIds?.[String(panelTabId)];

    return sessionId ? data.discussions?.[sessionId] ?? null : null;
}

/**
 * Reads the source tab id bound into this side panel document URL.
 */
function getPanelTabId(): number | null {
    const tabId = new URLSearchParams(location.search).get("tabId");
    if (!tabId) {
        return null;
    }

    const parsed = Number(tabId);
    return Number.isInteger(parsed) ? parsed : null;
}
