const CHATGPT_BASE_URL = "https://chatgpt.com/";

const sourceTitleEl = document.getElementById("sourceTitle") as HTMLDivElement | null;
const sourceUrlEl = document.getElementById("sourceUrl") as HTMLDivElement | null;
const copyPromptBtn = document.getElementById("copyPromptBtn") as HTMLButtonElement | null;
const reinsertBtn = document.getElementById("reinsertBtn") as HTMLButtonElement | null;
const closeBtn = document.getElementById("closeBtn") as HTMLButtonElement | null;
const chatgptFrame = document.getElementById("chatgptFrame") as HTMLIFrameElement | null;

/**
 * Extension session id currently loaded into the ChatGPT iframe.
 *
 * This is not a ChatGPT conversation or thread id. It is generated by the
 * extension in background.ts, stored in chrome.storage.local, and passed to
 * ChatGPT in the iframe URL hash as dwc_session=... so the content script can
 * match the iframe page to the prompt it should insert.
 *
 * The side panel starts with no iframe session loaded, so this value is null.
 * During startup, storage changes, and active-tab changes, the side panel reads
 * the active tab's extension session id from storage. When that id differs from
 * this local value, the side panel updates this value to the new id and
 * navigates the iframe to a ChatGPT URL containing that session hash.
 *
 * Keeping this local copy prevents repeated storage or tab-activation events
 * from reloading the iframe for the same session, which would discard the
 * current ChatGPT composer state.
 */
let currentIframeSessionId: string | null = null;

void init();

async function init(): Promise<void> {
    if (!sourceTitleEl || !sourceUrlEl || !copyPromptBtn || !reinsertBtn || !closeBtn || !chatgptFrame) {
        console.error("[discuss-with-chatgpt-ext] side panel DOM elements not found");
        return;
    }

    await renderSource();
    await syncIframeSession();
    attachEvents();

    // storage changes are the side panel's primary signal that the active tab
    // received a new prompt or session mapping
    chrome.storage.onChanged.addListener(async (changes, areaName) => {
        if (areaName !== "local") {
            return;
        }

        if (changes["discussions"] || changes["tabSessionIds"]) {
            await renderSource();
            await syncIframeSession();
        }
    });

    // the active tab can change without storage changing, so refresh visible
    // metadata and iframe state on activation too
    chrome.tabs.onActivated.addListener(() => {
        void renderSource();
        void syncIframeSession();
    });
}

/**
 * Binds side panel controls for copying, reinserting, and closing the current
 * discussion session.
 */
function attachEvents(): void {
    copyPromptBtn?.addEventListener("click", async () => {
        const discussion = await getActiveDiscussion();
        await navigator.clipboard.writeText(discussion?.prompt ?? "");
    });

    reinsertBtn?.addEventListener("click", async () => {
        const activeTabId = await getActiveTabId();
        if (activeTabId === null) {
            return;
        }

        const storage = (await chrome.storage.local.get([
            "discussions",
            "tabSessionIds"
        ])) as StorageShape;
        const sessionId = storage.tabSessionIds?.[String(activeTabId)];
        if (!sessionId || !storage.discussions?.[sessionId]) {
            return;
        }

        const discussions = { ...storage.discussions };

        // bumping stamp and resetting consumed makes the content script treat
        // this existing prompt as a new insertion request
        discussions[sessionId] = {
            ...discussions[sessionId],
            stamp: Date.now(),
            consumed: false
        };

        await chrome.storage.local.set({ discussions });
    });

    closeBtn?.addEventListener("click", async () => {
        const activeTabId = await getActiveTabId();
        if (activeTabId === null) {
            return;
        }

        const storage = (await chrome.storage.local.get([
            "discussions",
            "tabSessionIds"
        ])) as StorageShape;
        const tabKey = String(activeTabId);
        const sessionId = storage.tabSessionIds?.[tabKey];
        const discussions = { ...(storage.discussions ?? {}) };
        const tabSessionIds = { ...(storage.tabSessionIds ?? {}) };

        if (sessionId) {
            delete discussions[sessionId];
            delete tabSessionIds[tabKey];
        }

        await chrome.storage.local.set({
            discussions,
            tabSessionIds,
            closeDiscussionSessionId: sessionId
        });

        // give the content script a short window to observe closeDiscussionSessionId
        // and remove ChatGPT's transient draft before the panel tears down
        await new Promise((resolve) => setTimeout(resolve, 150));

        window.close();
    });
}

/**
 * Renders the source title and URL for the active tab's current discussion.
 */
async function renderSource(): Promise<void> {
    if (!sourceTitleEl || !sourceUrlEl) {
        return;
    }

    const discussion = await getActiveDiscussion();
    const source = discussion?.source;

    if (!source) {
        sourceTitleEl.textContent = "Page not selected";
        sourceUrlEl.textContent = "URL not found";
        return;
    }

    sourceTitleEl.textContent = source.title || "Page title is missing";
    sourceUrlEl.textContent = source.url || "URL is missing";
}

/**
 * Keeps the embedded ChatGPT frame aligned with the active browser tab's
 * discussion session.
 *
 * The background script creates one extension session id per source tab and
 * stores that mapping in chrome.storage.local.tabSessionIds. The side panel can
 * be notified for the same tab/session more than once during startup, storage
 * updates, and tab activation, so this function treats storage as the source of
 * truth and only navigates the iframe when the desired session actually changes.
 *
 * Navigating the iframe is meaningful because buildChatUrl embeds the session
 * id in the ChatGPT URL hash. The content script running inside ChatGPT reads
 * that hash, looks up the matching stored prompt, and inserts it into the
 * composer.
 *
 * Reassigning chatgptFrame.src for the same session would reload ChatGPT and
 * can discard the user's current unsent composer text, so currentIframeSessionId
 * is used as a local reload guard.
 */
async function syncIframeSession(): Promise<void> {
    if (!chatgptFrame) {
        return;
    }

    const activeTabId = await getActiveTabId();
    if (activeTabId === null) {
        return;
    }

    const data = (await chrome.storage.local.get("tabSessionIds")) as StorageShape;
    const sessionId = data.tabSessionIds?.[String(activeTabId)];

    // loading the same session again would reload ChatGPT and discard the
    // current composer state
    if (!sessionId || sessionId === currentIframeSessionId) {
        return;
    }

    currentIframeSessionId = sessionId;
    chatgptFrame.src = buildChatUrl(sessionId);
}

/**
 * Creates the ChatGPT URL that carries the extension session id in the hash.
 *
 * The hash is intentionally extension-owned state, not a ChatGPT conversation
 * id. It lets the ChatGPT content script identify which discussion entry in
 * chrome.storage.local belongs to this iframe load.
 */
function buildChatUrl(sessionId: string): string {
    const url = new URL(CHATGPT_BASE_URL);
    url.hash = `dwc_session=${encodeURIComponent(sessionId)}`;
    return url.toString();
}

/**
 * Returns the discussion state associated with the currently active browser tab.
 */
async function getActiveDiscussion(): Promise<DiscussionState | null> {
    const activeTabId = await getActiveTabId();
    if (activeTabId === null) {
        return null;
    }

    const data = (await chrome.storage.local.get([
        "discussions",
        "tabSessionIds"
    ])) as StorageShape;
    const sessionId = data.tabSessionIds?.[String(activeTabId)];

    return sessionId ? data.discussions?.[sessionId] ?? null : null;
}

/**
 * Looks up the active tab id in the current browser window.
 */
async function getActiveTabId(): Promise<number | null> {
    const [tab] = await chrome.tabs.query({
        active: true,
        currentWindow: true
    });

    return typeof tab?.id === "number" ? tab.id : null;
}
